name: Direct Manual Deploy

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Deployment message'
        required: false
        default: 'Manual deployment test'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: List files for debugging
        run: |
          echo "=== Repository Files ==="
          ls -la
          echo "=== Index.html check ==="
          cat index.html || echo "No index.html found"
          
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          app_location: '/'
          output_location: ''
          skip_app_build: true
        env:
          DEPLOYMENT_MESSAGE: ${{ github.event.inputs.message }}