name: Minimal Deployment Test

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: List root files
        run: |
          echo "=== ROOT DIRECTORY ==="
          ls -la
          echo "=== INDEX.HTML CHECK ==="
          test -f index.html && echo "index.html EXISTS" || echo "index.html MISSING"
          test -f index.html && cat index.html || echo "Cannot read index.html"
          
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          skip_app_build: true
          skip_api_build: true