name: Simple Secret Test

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secret
        run: |
          echo "Testing secret availability..."
          echo "Secret exists: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN != '' }}"
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "❌ AZURE_STATIC_WEB_APPS_API_TOKEN is empty or not set"
            exit 1
          else
            echo "✅ AZURE_STATIC_WEB_APPS_API_TOKEN is set"
            echo "Token length: $(echo '${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}' | wc -c)"
          fi