name: Test Secret Access

on:
  workflow_dispatch: # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Secret
        run: |
          echo "Testing secret access..."
          if [ -n "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "✅ Secret AZURE_STATIC_WEB_APPS_API_TOKEN is accessible"
            echo "Secret length: $(echo '${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}' | wc -c)"
          else
            echo "❌ Secret AZURE_STATIC_WEB_APPS_API_TOKEN is NOT accessible"
          fi
        env:
          TEST_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}